navbar final
gdsc-nits-org/grafiny-client pull request #12
Opened 2023-01-15 10:56 UTC by smasoom

responsive grafiny navbar

2023-01-15 11:12 UTC, resyfer requested changes

2023-01-15 11:12 UTC, resyfer commented on src/Components/Navbar/Navbar.module.scss
> +  box-shadow: 0px 4px 12px 0px var(--gdsc-shadow-1-100);
Make box shadows have relative units, not absolute units like px

2023-01-19 11:21 UTC, resyfer approved these changes

2023-01-29 13:07 UTC, resyfer commented
There are some spacing issues. The space to left of hamburger icon and right of profile icon are same in design:

Design:
![image](https://user-images.githubusercontent.com/74897008/215327976-e8cd3b4d-27b5-437f-b4fc-be076f71f304.png)

Code:
![image](https://user-images.githubusercontent.com/74897008/215327997-307ff529-5500-48df-a3ff-cc34bdc722f7.png)

Use flexbox for styling the 3 elements in navbar in mobile view (when closed), not right/left distance.

2023-02-02 06:08 UTC, codadept approved these changes

2023-02-02 06:09 UTC, merged