ADD: Search Results Page
gdsc-nits-org/grafiny-client pull request #22
Opened 2023-01-28 14:31 UTC by AnubhavChakrabortynits

Fixed Explore Component of Home Page

Added a new  page  -> Search Results

@codadept @resyfer

2023-02-02 06:14 UTC, codadept commented
Take a pull from `dev` and push the merge commit

2023-02-02 13:20 UTC, AnubhavChakrabortynits commented
Pulled From Dev..

Also Fixed Navbar position from fixed to sticky 

@codadept @resyfer

2023-02-13 18:03 UTC, codadept requested changes
Mimic a demo search feature for your front-end. Create a json file in /public as follows

`/public/db/courses.json`

Which will contain an array of courses. Use fetch all the array of courses as follows

```js
fetch("/db/courses.json")
```

User proper state variable to store the courses (array) and then take the input from the user in the search input and then use proper array method to filter out the courses with that name and then display the result list as SearchResultItem. 

Pass the necessary data like course name, id etc. to the SearchResultItem as props from the parent component where you will get the course data.

2023-02-15 17:18 UTC, AnubhavChakrabortynits commented
Json file with dummy data added

SearchResults function added

2023-02-22 09:04 UTC, codadept requested changes
By default the search result should display all the courses. And only display the filtered course when the user searches

2023-02-22 09:04 UTC, codadept commented on src/Pages/SearchResults/Searchresults.jsx
> +  const [course, setCourse] = useState(() => "");
Passing an anonymous function as parameter for useState is redundant

2023-02-22 09:04 UTC, codadept commented on src/Pages/SearchResults/Searchresults.jsx
> +    const regularExp = new RegExp(`${course}`);
No need to pass javascript variables as `${course}` as it in not inside return keyword.

2023-02-22 09:04 UTC, codadept commented on src/Pages/SearchResults/Searchresults.jsx
> +  };
Don't need to use regex. just use string includes, because ultimately the search will be done in the backend and we won't use Regex

2023-02-22 13:25 UTC, AnubhavChakrabortynits commented
Fixed the search results function.

2023-02-24 08:21 UTC, codadept approved these changes

2023-02-24 08:22 UTC, merged