ADD: Semester page
gdsc-nits-org/grafiny-client pull request #25
Opened 2023-01-30 18:31 UTC by HrishB16

Please review and merge it

2023-02-02 06:15 UTC, codadept commented
Take a pull from `dev` branch and push the merge commit

2023-02-11 04:11 UTC, resyfer commented
Semester Page:

Laptop:
![image](https://user-images.githubusercontent.com/74897008/218238234-bc9b930d-7024-495f-84b1-73a255f53b80.png)

Mobile:
![image](https://user-images.githubusercontent.com/74897008/218238267-8c6e3d8f-c67c-477f-8a07-2f792039b086.png)

![image](https://user-images.githubusercontent.com/74897008/218238305-18b42b38-8886-41ad-a063-92d8cdb728b8.png)

Same issue for Topics page.

Fix it.

Also change (yet again) every absolute unit in the css you wrote to a relative unit.

2023-02-18 08:10 UTC, resyfer requested changes
Topics:

![image](https://user-images.githubusercontent.com/74897008/219849470-52d764ab-ee3c-4942-9ede-ced7e8ff6357.png)

Scrollbar at right within the topics box. Also remove horizontal. Fix it. Do NOT remove the scrollbar using display property. Instead increase the height (dynamically, to have as many items as needed in it), and remove horizontal scrollbar by fixing the main issue in it.

Same issues with Semester

2023-02-23 02:12 UTC, resyfer requested changes

2023-02-23 02:12 UTC, resyfer commented on src/Components/Semester/Semester.module.scss
> +  width: 98vw;
Changing 100vw to 98vw for removing horizontal scrollbar is absurd. Use 100% for width.

Please google stuff like this before using maths to accomplish it, as that maths will most likely only work on your PC.

2023-02-23 02:12 UTC, resyfer commented on src/Components/Semester/Semester.module.scss
> +    width: 100vw;
Same issue here

2023-02-23 02:12 UTC, resyfer commented on src/Components/Topics/Topics.module.scss
> +  width: 98vw;
Again

2023-02-23 02:12 UTC, resyfer commented on src/Components/Topics/Topics.module.scss
> +    width: 100vw;
And again

2023-03-02 18:22 UTC, merged