LoginPage
gdsc-nits-org/grafiny-client pull request #29
Opened 2023-02-25 19:06 UTC by Prag03

- login page added
- html and css used

2023-02-26 19:24 UTC, codadept requested changes
1) Delete the Facebook.png and Google.png from `public/` and `src/Pages/Login/` because you are using the images from `public/assets/`

2) Suggestion: If you need to use images then always put the images in public directory.

Suppose you image is in `/public/assets/background.png`

and to use it you have to write the source of the image as

```html
<img src="/assets/background.png" alt="background"/>
```

```css
.class-name{
    background-image: url("/assets/background.png");
}
```

because vite servers the public directory as root (/). [Checkout](https://vitejs.dev/guide/assets.html#the-public-directory)

3) Complete the styling of the page

2023-02-26 19:24 UTC, codadept commented on package.json
> +    "@material-ui/icons": "^4.11.3",
Uninstall these libraries as it's not being used

2023-02-26 19:24 UTC, codadept commented on src/Pages/Login/Login.jsx
> +    </div>
Check how to handle form input in react. By handle I mean, I need you to store the form input data (email, password...) in a React state such that it's two way data binding. i.e

1) When user updates the value in HTML element it get's updated in the React state
2) When we update the data in React state, it gets updated in the DOM.

[Checkout this article on Controlling Form Input (multiple)](https://ibaslogic.com/simple-guide-to-react-form/#controlled-react-form-input)

2023-03-21 17:50 UTC, Prag03 commented
Changes done.
New pages added.
RecoveryMail URL : http://localhost:3000/forgotpassword
RecoveryCode URL : http://localhost:3000/sendotp
ResetPassword URL : http://localhost:3000/verified

2023-03-22 10:25 UTC, codadept commented
@Prag03 The numbers are not visible. Maybe a padding issue. Fix it

![image](https://user-images.githubusercontent.com/63517465/226874490-62595656-dff4-4b1e-8b1c-fb263fc424b5.png)

2023-03-22 10:27 UTC, codadept requested changes

2023-03-22 10:27 UTC, codadept commented on src/Pages/RecoveryCode/RecoveryCode.jsx
> +          </a>
For internal links use

`Link` component from `react-router-dom`

2023-03-22 20:22 UTC, Prag03 commented
Fixed bugs.
Changes done.

2023-03-23 19:57 UTC, codadept approved these changes
Good job!

2023-03-23 20:08 UTC, merged