Anubhav: Explore Component of HomePage implemented
gdsc-nits-org/grafiny-client pull request #3
Opened 2023-01-08 06:53 UTC by AnubhavChakrabortynits

commit-1: Made The Explore Component

commit-2: Explore Component Made Responsive for all breakPoints 

commit-3: Changing Text Animation Added in the title

commit-4 Minor glitches in the animation as well as the animation duration was increased..

2023-01-08 08:24 UTC, codadept requested changes

2023-01-08 08:24 UTC, codadept commented on src/Components/Explore/Explore.jsx
> +           <img src={image} alt="" />
Add alt text

2023-01-08 08:24 UTC, codadept commented on src/Components/Explore/Explore.module.scss
> +            font-family: 'Poppins';
No need to add font-family for all the elements, as its mentioned in index.scss for entire HTML elements

2023-01-08 08:32 UTC, codadept commented on src/Components/Explore/Explore.jsx
> +export default function Explore() {
I have written an eslint rule to throw warning for the rule `react/function-component-definition`

Rule definition states that

> This rule is aimed to enforce consistent function types for function components. By default it prefers function declarations for named components and function expressions for unnamed components.

And by convention the function definition is preferred to be an arrow function.

So, first create an arrow function

```jsx
const Explore = () => {}
```

and then export it in the end

```jsx
export default Explore;
```

2023-01-08 09:19 UTC, codadept commented
Few more changes required

(Following convention)
- The `Roboto` font is not imported. Import the font from [Google Fonts](https://fonts.google.com) in `index.scss` as done for Poppins font. Declare a variable naming `--gdsc-font-2` for Roboto as done for Poppins and use that variable in your Explore.module.scss.

(Following convention)
- Whatever color you are using in your scss, first check whether there is some variable in `index.scss` with that color value (most probably there will be because we are following a theme) and if not present then make a variable in `:root` in index.scss and then use that color in your scss file using `var()`

(Best practices)
- For the image `exploreimg.png`, move the image to `public/` by creating a directory such as assets and then you will be accessing the image as follows

        Suppose the image is in the following path
        `public/assets/exploreimg.png`
        
        Then you will be accessing it as 

```html
<img src="/assets/exploreimg.png" alt="Explore Image"/>
```

[Reference](https://vitejs.dev/guide/assets.html#the-public-directory)

(Following convention)
- Use the components in the following manner. As for the `Explore` Component, `src/Components/index.jsx` should contain the following lines

```jsx
import Explore from "./Explore/Explore";
import Button from "./Button/Button";
import Navbar from "./Navbar/Navbar";

export { Button, Navbar, Explore };
```

And for importing the Component in any of the file

```jsx
import { Button, Explore } from "../../Components";
```

2023-01-08 09:31 UTC, codadept commented
![image](https://user-images.githubusercontent.com/63517465/211189130-245cc03a-e320-4a74-b588-b03273216e6c.png)

Also increase the vertical padding of the input element a bit more to match with the design

2023-01-08 15:08 UTC, AnubhavChakrabortynits commented
Made Changes as suggested..

Also , Increased the vertical padding of the search bar a bit... (10px - > 25px)

2023-01-09 13:53 UTC, codadept approved these changes

2023-01-09 13:58 UTC, codadept approved these changes

2023-01-09 13:58 UTC, codadept commented
Ready to merge @AnubhavChakrabortynits ?

2023-01-09 14:00 UTC, merged