Navbar: Bug Fix
gdsc-nits-org/grafiny-client pull request #33
Opened 2023-03-23 07:01 UTC by smasoom

2023-03-23 12:19 UTC, resyfer requested changes
The contents of the navbar are shifted up from centre. Pls fix:
![image](https://user-images.githubusercontent.com/74897008/227201532-6a580b08-1a8b-4e7e-92a7-6726017a1c07.png)

Also there's some more spacing in the left in the design:
![image](https://user-images.githubusercontent.com/74897008/227201678-b90810f6-6bfa-40e7-912f-a1148fbc3339.png)

2023-03-23 12:19 UTC, resyfer commented on src/Components/Navbar/Navbar.module.scss
> +  box-shadow: 0px 4px 12px 0px var(--gdsc-grayish-2-100);
Pixels -> Relative Units

2023-05-12 09:31 UTC, resyfer requested changes
![image](https://github.com/gdsc-nits-org/grafiny-client/assets/74897008/cfeb26d8-7561-42fc-9a3b-c106a2c0abed)

I think instead of margin from top, you should centre it in vertical using flex. And also, to make flex work, I don't think absolute positioning will do. And absolute is not required as well in your case.

So make it relative, and vertical centre using flex and justify-content and align-items as centre.

2023-06-11 10:18 UTC, codadept approved these changes

2023-06-11 10:18 UTC, merged