ADD: auth context and signup login functions
gdsc-nits-org/grafiny-client pull request #35
Opened 2023-04-03 18:34 UTC by AnubhavChakrabortynits

2023-05-12 18:01 UTC, codadept requested changes
Move your login/signup code to the auth context itself and handle it there and in the Login/Signup component just call the corresponding context functions. 

Change your code accordingly

2023-05-12 18:01 UTC, codadept commented on .env
> +VITE_LOGIN_URL="http://localhost:5000/api/v1/auth/login"
Don't use individual routes in environment variables.

Just add `VITE_BASE_URL="http://localhost:5000/api/v1"`

and use it in js as 

```js
`${import.meta.env.VITE_BASE_URL}/auth/login`
```

2023-05-12 18:02 UTC, codadept commented
Also fix the merge conflicts

2023-05-15 17:47 UTC, AnubhavChakrabortynits commented
made changes as requested

2023-05-18 03:57 UTC, codadept approved these changes

2023-05-18 03:57 UTC, codadept commented on src/Global/Auth/authContext.js
> +const UserContext = createContext();
Pass the default value in `React.createContext`

2023-05-18 05:05 UTC, AnubhavChakrabortynits commented
deafult value provided

2023-05-20 04:21 UTC, codadept requested changes

2023-05-20 04:21 UTC, codadept commented on src/Global/Auth/authContext.js
> +const UserContext = createContext("User");
Default value means the object you are storing in the context. e.g.

```js

const UserContext = createContext({
    username: "",
    email: "",
    address: {
        street: "",
        city: "",
    }
});
```

Whatever it is according to your context.

2023-06-10 10:25 UTC, AnubhavChakrabortynits commented
Fixed default value of authContext

2023-06-10 11:08 UTC, codadept approved these changes

2023-06-10 11:08 UTC, merged